name: coffee-rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - biopython
  - salmon=1.10.3
  - fastqc
  - multiqc
  - pigz
  - r-base
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-tibble
  - r-jsonlite
  - r-openxlsx
  - bioconductor-deseq2
  - bioconductor-tximport
  - star
  - gffread
  - samtools
